spring:
  profiles:
    active: dev
  datasource:
    url: 'jdbc:mysql://localhost:3306/online-teach?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true'
    username: 'root'
    password: 'root'
    driverClassName: 'com.mysql.cj.jdbc.Driver'
  jpa:
    database: MYSQL
    show-sql: false # Show or not log for each sql query
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  main:
#    allow-bean-definition-overriding: true
server:
  port: 8877
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

